generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    
    config:
      fields: ~

      list:
        title:   User list
        display: [=username, fullname, created_at, updated_at, last_login]

      form:
        class: sfGuardUserForm
        display:
          "User":                   [first_name, last_name, email_address, username, _password]
          "Permissions and groups": [is_active, is_super_admin, groups_list]

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User