<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object CommentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Comment');
  }
  public function getTreeForFile($file_id)
  {
    $q = $this->createQuery('g')
      ->orderBy('g.root_id')
      ->addOrderBy('g.lft')
      ->where('g.file_id = ?', $file_id)
    ;
    $tree = $q->execute(array(),  Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);
  
    return $tree;
  }
}