<?php

/**
 * File
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    www
 * @subpackage model
 * @author     Dziamid Zayankouski
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class File extends BaseFile
{
  /**
  * Generate filename for uploaded files
  *
  */
  public function generateNameFilename(sfValidatedFile $file)
  {
    return $file->getOriginalName();
  }
  /**
   * Unlink related file when deleting a record
   *
   */
  public function delete(Doctrine_Connection $conn = null)
  {
    $path = sfConfig::get('sf_upload_dir') . '/' . $this->getName();
    @unlink($path);
    return parent::delete($conn);
  }
  
  /**
   * Checks if file has comment relations
   * 
   * @return boolean
   */
  public function hasComments()
  {
    return $this->getComments()->count() !== 0;
  }

}
