all:
  sf_guard_plugin:
    routes_register: false
    remember_key_expiration_age:  1209600
    #remember_cookie_name:         wwwFrontendRememberMe
    #retrieve_by_username_callable: sfGuardUser::getForFrontendAuth
    success_signin_url: file
    success_signout_url: homepage
    
  sfApplyPlugin:
    from:
      email: "belgim.ovs@gmail.com"
      fullname: "belgim.by"

  sfForkedApply:
    routes:
      apply: /user/new
      reset: /user/password-reset
      resetRequest: /user/reset-request
      resetCancel: /user/reset-cancel
      validate: /user/confirm/:validate
      settings: /user/settings
      
  reply_level_limit: 3
  
  .settings: #dot notation to return the following as an array
    menu:
      - homepage
      - file
      - file_new
    