file_public:
  class: sfDoctrineRouteCollection
  options:
    actions: [list]
    model:                File
    module:               filePublic
    prefix_path:          /public
    #with_wildcard_routes: true

file_show:
  url:  /file/:id
  options:
    module: file
    action: show
file:
  class: sfDoctrineRouteCollection
  options:
    module: file
    model: File
    object_actions:
      comment: post
    with_wildcard_routes: true
    
#sfDoctrineGuardPlugin
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

homepage:
  url:   /
  param: { module: filePublic, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
