<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    www
 * @subpackage model
 * @author     Dziamid Zayankouski
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  /**
   * String representation of a sfGuardUser object
   */
  public function  __toString()
  {
    if($this->getFirstName() !== null || $this->getLastName() !== null)
    {
      return $this->getFullname();
    }
    else
    {
      return $this->getUsername();
    }
  }
  /**
   * Returns joined first_name and last_name as fullname.
   * 
   * @return string
   */
  public function getFullname()
  {
    return trim($this->getFirstName().' '.$this->getLastName());
  }
}
