generator:
  class: sfDoctrineGenerator
  param:
    model_class:           File
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          file
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: {label: Upload date, date_format: d MMM yyyy HH:mm }
      list:
        title: Files list
        table_method: getForUser
        display: [_name, is_public, created_at]
        max_per_page: 25
        sort: ['created_at','desc']
      filter:  ~
      form:    ~
      edit:
        title: Edit File "%%name%%"
      new:     ~
