generator:
  class: sfDoctrineGenerator
  param:
    model_class:           File
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          file_public
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at: {label: Upload date, date_format: d MMM yyyy HH:mm }
      list:
        table_method: getForPublic
        display: [_name, created_at]
        max_per_page: 25
        sort: ['created_at','desc']
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
