<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    www
 * @subpackage model
 * @author     Dziamid Zayankouski
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class sfGuardUserProfile extends PluginsfGuardUserProfile
{
  public function  __toString()
  {
    return $this->getUser()->__toString();
  }
  /**
   * Returns joind firstname and lastname as fullname.
   * @return string
   * @author fizyk
   */
  public function getFullname()
  {
    return $this->getUser()->getFullname();
  }
}
