File:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    user_id: integer
    user_browser: string(255)
    user_ip: string(255)
    is_public:
      type: boolean
      notnull: true
      default: true
  relations:
    sfGuardUser:
      alias: User
      foreignAlias: Files
      local: user_id
      foreign: id
      onDelete: CASCADE

    
Comment:
  actAs:
    NestedSet:
      hasManyRoots: true
    Timestampable: ~
  columns:
    username:
      type: string(30)
      notnull: true
    file_id: integer
    root_id: integer
    message:
      type: string(1020)
      notnull: true
  relations:
    File:
      local: file_id
      foreign: id
      foreignAlias: Comments
      onDelete: CASCADE