File:
  columns:
    name: string(255)
    
Comment:
  actAs:
    NestedSet:
      hasManyRoots: true
      
  columns:
    username:
      type: string(30)
      notnull: true
    file_id: integer
    root_id: integer
    message:
      type: string(1020)
      notnull: true
  relations:
    File:
      local: file_id
      foreign: id
      foreignAlias: Comments